ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [com.shaka.ApplicationKt.module]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/shaka"
    url = ${?DATABASE_URL}
    driver = "org.postgresql.Driver"
    user = "shaka"
    user = ${?DATABASE_USER}
    password = ""
    password = ${?DATABASE_PASSWORD}
}

redis {
    url = "redis://localhost:6379"
    url = ${?REDIS_URL}
}

api {
    openMeteo {
        baseUrl = "https://api.open-meteo.com/v1"
    }
    copernicus {
        baseUrl = "https://nrt.cmems-du.eu/motu-web/Motu"
        user = ${?COPERNICUS_USER}
        password = ${?COPERNICUS_PASSWORD}
    }
    noaa {
        baseUrl = "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter"
    }
}
